version: '3'

services:
  web:
    build: .
    ports:
      - '3000:3000'
      - '4000:4000' # for testing using selenium
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/database
      - .env/development/web
    environment:
      # So that the web service knows where to find the webpack dev server
      - WEBPACKER_DEV_SERVER_HOST=webpack-dev-server
  redis:
    image: redis
  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data
  webpack-dev-server:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/database
      - .env/development/web
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    ports:
      - '3035:3035'
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - '4444:4444'
      - '7900:7900'
    shm_size: '2g'
volumes:
    db_data: